import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  'English (US)': {
    home: 'Home',
    trips: 'Trips',
    tracking: 'Live Map',
    profile: 'Profile',
    bus_info: 'Bus Info',
    notifications: 'Alerts',
    settings: 'Settings',
    search: 'Search...',
    driver: 'Driver',
    speed: 'Speed',
    distance: 'Distance',
    upcoming: 'Upcoming',
    completed: 'Completed',
    morning: 'Morning',
    evening: 'Evening',
    logout: 'Logout',
    student_details: 'Student Details',
    app_settings: 'App Settings',
    privacy: 'Privacy & Security',
    help: 'Help & Support',
    morning_pickup: 'Morning Pickup',
    evening_drop: 'Evening Drop',
    dashboard_title: 'School Bus Tracker',
    transit_pass: 'Transit Pass',
    active: 'Active',
    boarding_point: 'Boarding Point',
    assigned_bus: 'Assigned Bus',
    transit_status: 'Transit Status',
    bus_arriving_in: 'Bus Arriving In',
    min: 'Min',
    km_away: 'KM AWAY',
    track_now: 'Track Now',
    vehicle_details: 'Vehicle Details',
    trip_logs: 'Trip Logs',
    history: 'History',
    todays_overview: "Today's Overview",
    picked_up: 'Picked Up',
    in_transit: 'In Transit',
    eta_school: 'ETA School',
    expected_drop: 'Expected Drop',
    grade: 'Grade',
    personal_details: 'Personal Details',
    mobile_number: 'Mobile Number',
    email_address: 'Email Address',
    residential_address: 'Residential Address',
    control_center: 'Control Center'
  },
  'Hindi': {
    home: 'होम',
    trips: 'यात्राएं',
    tracking: 'लाइव मैप',
    profile: 'प्रोफ़ाइल',
    bus_info: 'बस जानकारी',
    notifications: 'अलर्ट',
    settings: 'सेटिंग्स',
    search: 'खोजें...',
    driver: 'ड्राइवर',
    speed: 'गति',
    distance: 'दूरी',
    upcoming: 'आगामी',
    completed: 'पूरा हुआ',
    morning: 'सुबह',
    evening: 'शाम',
    logout: 'लॉगआउट',
    student_details: 'छात्र विवरण',
    app_settings: 'ऐप सेटिंग्स',
    privacy: 'गोपनीयता और सुरक्षा',
    help: 'सहायता और समर्थन',
    morning_pickup: 'सुबह की पिकअप',
    evening_drop: 'शाम की ड्रॉप',
    dashboard_title: 'स्कूल बस ट्रैकर',
    transit_pass: 'ट्रांजिट पास',
    active: 'सक्रिय',
    boarding_point: 'बोर्डिंग बिंदु',
    assigned_bus: 'आवंटित बस',
    transit_status: 'पारगमन स्थिति',
    bus_arriving_in: 'बस आ रही है',
    min: 'मिनट',
    km_away: 'किमी दूर',
    track_now: 'अभी ट्रैक करें',
    vehicle_details: 'वाहन विवरण',
    trip_logs: 'ट्रिप लॉग्स',
    history: 'इतिहास',
    todays_overview: "आज का अवलोकन",
    picked_up: 'पिक अप हो गया',
    in_transit: 'रास्ते में',
    eta_school: 'ईटीए स्कूल',
    expected_drop: 'अपेक्षित ड्रॉप',
    grade: 'कक्षा',
    personal_details: 'व्यक्तिगत विवरण',
    mobile_number: 'मोबाइल नंबर',
    email_address: 'ईमेल पता',
    residential_address: 'आवासीय पता',
    control_center: 'नियंत्रण केंद्र'
  },
  'Tamil': {
    home: 'முகப்பு',
    trips: 'பயணங்கள்',
    tracking: 'நேரலை வரைபடம்',
    profile: 'சுயவிவரம்',
    bus_info: 'பேருந்து தகவல்',
    notifications: 'அறிவிப்புகள்',
    settings: 'அமைப்புகள்',
    search: 'தேடல்...',
    driver: 'ஓட்டுநர்',
    speed: 'வேகம்',
    distance: 'தூரம்',
    upcoming: 'வரவிருக்கும்',
    completed: 'முடிந்தது',
    morning: 'காலை',
    evening: 'மாலை',
    logout: 'வெளியேறு',
    student_details: 'மாணவர் விவரங்கள்',
    app_settings: 'பயன்பாட்டு அமைப்புகள்',
    privacy: 'தனியுரிமை மற்றும் பாதுகாப்பு',
    help: 'உதவி மற்றும் ஆதரவு',
    morning_pickup: 'காலை பிக்கப்',
    evening_drop: 'மாலை டிராப்',
    dashboard_title: 'பள்ளி பேருந்து டிராக்கர்',
    transit_pass: 'போக்குவரத்து பாஸ்',
    active: 'செயலில்',
    boarding_point: 'ஏறும் இடம்',
    assigned_bus: 'ஒதுக்கப்பட்ட பேருந்து',
    transit_status: 'போக்குவரத்து நிலை',
    bus_arriving_in: 'பேருந்து வருகிறது',
    min: 'நிமிடம்',
    km_away: 'கி.மீ தூரம்',
    track_now: 'இப்போது தேடு',
    vehicle_details: 'வாகன விவரங்கள்',
    trip_logs: 'பயண பதிவுகள்',
    history: 'வரலாறு',
    todays_overview: "இன்றைய கண்ணோட்டம்",
    picked_up: 'ஏற்றப்பட்டது',
    in_transit: 'பயணத்தில்',
    eta_school: 'பள்ளிக்கு வரும் நேரம்',
    expected_drop: 'எதிர்பார்க்கப்படும் இறக்கம்',
    grade: 'வகுப்பு',
    personal_details: 'தனிப்பட்ட விவரங்கள்',
    mobile_number: 'மொபைல் எண்',
    email_address: 'மின்னஞ்சல் முகவரி',
    residential_address: 'குடியிருப்பு முகவரி',
    control_center: 'கட்டுப்பாட்டு மையம்'
  },
  'English (UK)': {
    home: 'Home',
    trips: 'Trips',
    tracking: 'Live Map',
    profile: 'Profile',
    bus_info: 'Bus Info',
    notifications: 'Alerts',
    settings: 'Settings',
    search: 'Search...',
    driver: 'Driver',
    speed: 'Speed',
    distance: 'Distance',
    upcoming: 'Upcoming',
    completed: 'Completed',
    morning: 'Morning',
    evening: 'Evening',
    logout: 'Logout',
    student_details: 'Student Details',
    app_settings: 'App Settings',
    privacy: 'Privacy & Security',
    help: 'Help & Support',
    morning_pickup: 'Morning Pickup',
    evening_drop: 'Evening Drop',
    dashboard_title: 'School Bus Tracker',
    transit_pass: 'Transit Pass',
    active: 'Active',
    boarding_point: 'Boarding Point',
    assigned_bus: 'Assigned Bus',
    transit_status: 'Transit Status',
    bus_arriving_in: 'Bus Arriving In',
    min: 'Min',
    km_away: 'KM AWAY',
    track_now: 'Track Now',
    vehicle_details: 'Vehicle Details',
    trip_logs: 'Trip Logs',
    history: 'History',
    todays_overview: "Today's Overview",
    picked_up: 'Picked Up',
    in_transit: 'In Transit',
    eta_school: 'ETA School',
    expected_drop: 'Expected Drop',
    grade: 'Grade',
    personal_details: 'Personal Details',
    mobile_number: 'Mobile Number',
    email_address: 'Email Address',
    residential_address: 'Residential Address',
    control_center: 'Control Centre'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('app-language') || 'English (US)');

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const t = (key) => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS['English (US)'];
    return langDict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
